### ISSUE TITLE
[Feature] Refactoring project 

### ISSUE THREAD

**Issue by CaiJingLong** [CaiJingLong/flutter_photo_manager#102]
As the time for project creation increases, there are many redundant codes in the project, that are deleted after refactoring for subsequent maintenance.

Keep dart code. Refactoring code in native.

- [x] dart
- [x] android
- [x] ios

---

- [x] Observer: If you are in the process of browsing, you can take a screenshot or cut out the application to take pictures, etc.
- [x] New image and page conflict issues.

---
- [x] For android Q privacy.

**Comment by CaiJingLong** [comment]
This work will be done in the refactoring-project branch. New PR will not be accepted during this time.

**Comment by CaiJingLong** [comment]
The main function has been refactored and is doing api compatibility.
Now progress: https://github.com/CaiJingLong/flutter_photo_manager/commit/2903e1087a8b4aae5b8393ed02c34247d8b11d0d

**Comment by CaiJingLong** [comment]
The main process has been completed. The version 0.4.0 will be released in the near future.

**Comment by CaiJingLong** [comment]
Now the latest commit is f84a1275e0c3ec9369025cfcaa006d054365cc4b.

Import it like next:

```yaml
dependencies:
  photo_manager: 
    git:
      url: https://github.com/CaiJingLong/flutter_photo_manager.git
      ref: f84a1275e0c3ec9369025cfcaa006d054365cc4b
```
