### ISSUE TITLE
[BUG]安卓在某些机型获取不到一些视频文件

### ISSUE THREAD

**Issue by lumingyuan** [CaiJingLong/flutter_photo_manager#179]
原因是query的时候加了宽高的筛选导致没有查询到视频文件，我目前本地进行修改了IDBUtils.kt的getCondFromType方法在删选视频时忽略宽高条件：

    when (type) {
      1 -> {
        condString = "AND ${MediaStore.Files.FileColumns.MEDIA_TYPE} = ?"
        args.add(MediaStore.Files.FileColumns.MEDIA_TYPE_IMAGE.toString())

        condString += "AND $sizeCond"
        args.addAll(sizeArgs)
      }
      2 -> {
        condString = "AND ${MediaStore.Files.FileColumns.MEDIA_TYPE} = ?"
        args.add(MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO.toString())

        condString += "AND $durationCond"
        args.addAll(durationArgs)
      }
      else -> {
        condString = "AND (($typeKey = ? AND $sizeCond) OR ($typeKey = ? AND $durationCond))"
        args.add(MediaStore.Files.FileColumns.MEDIA_TYPE_IMAGE.toString())
        args.addAll(sizeArgs)
        args.add(MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO.toString())
        args.addAll(durationArgs)
      }
    }

**Comment by CaiJingLong** [comment]
I think this is same problem of #167 .
But the most root cause comes from #82.

**Comment by CaiJingLong** [comment]
So I should still remove the width and height filter of the video.

**Comment by CaiJingLong** [comment]
Can you try to use the master version?

```yaml
  photo_manager:
    git:
      url: https://github.com/CaiJingLong/flutter_photo_manager.git
      ref: 329ad37d0d1301f36f03cac014da95831b5a1729
```
