### ISSUE TITLE
[BUG][iOS]Failed to read video and then app crashed with uncaught error

### ISSUE THREAD

**Issue by juncaixinchi** [CaiJingLong/flutter_photo_manager#74]
**Describe the bug**

Failed to read video and then app crashed with uncaught error

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS12.2

**Error message**
```
<AVComposition 0x28316d3c0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key URL
```

**Error position**

https://github.com/CaiJingLong/flutter_photo_manager/blob/789c79bb06abf1023a992f4988e05a29405e3e25/ios/Classes/ImageScanner.m#L446

**Comment by CaiJingLong** [comment]
I haven't seen this before. Can you describe what's special about this Video?

**Comment by juncaixinchi** [comment]
我这边试着定位了一下具体的video，但是发现这个视频传输到其他手机就正常了，没法发给你。

具体来说 Photo上显示该视频时长是3s，点开后实际进度条是16s，传输给其他手机或应用后就是16s了（然后就都正常了），使用photo_manager读取的时候，duration是3s，然后读取originFile时就会报上述错误，然后导致App闪退。

所以希望能够在这个地方加个try catch

**Comment by juncaixinchi** [comment]
@CaiJingLong 能再看一下这个问题吗？

**Comment by CaiJingLong** [comment]
Try use the library at git ref:09c094e295b4495ffea81e2b4a725b4a98b45c23 

```yaml
  photo_manager:
   git: 
     url: https://github.com/CaiJingLong/flutter_photo_manager
     ref: 09c094e295b4495ffea81e2b4a725b4a98b45c23
```
